package com.company;


import com.google.gson.Gson;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.*;

/**
 *
 * @author Maite Ivan
 */
public class Ventana extends javax.swing.JFrame {

    JFileChooser seleccionar = new JFileChooser();
    String path;
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    Persona usuario;
    Persona usuarioPantalla;
    Gson objGson;



    /**
     * Creates new form ventana
     */



    public Ventana() {
        initComponents();

    }

///

    public String GuardarArchivo(File archivo, String documento){

        String mensaje=null;

        try{


            salida = new FileOutputStream(archivo);
            byte[] byjson = documento.getBytes();
            salida.write(byjson);
            mensaje = "Usuario Registrado Con Éxito";


        }catch (Exception e){}

        return mensaje;


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        path = "C:\\Maite\\Tec. sup. Programación\\Programacion III\\Archivos TXT\\Usuario.json";
        archivo = new File(path);
        objGson = new Gson();
        usuario = new Persona();
        usuarioPantalla = new Persona();
        Registarse = new javax.swing.JFrame();
        PantallaPrincipal = new javax.swing.JFrame();
        PanelBajoPantallaPrincipal = new javax.swing.JPanel();
        PanelAeroTaxiPantallaPrincipal = new javax.swing.JPanel();
        LabelAeroTaxiPPrincipal = new javax.swing.JLabel();
        TextUsuarioPantallaPrincipal = new javax.swing.JTextField();
        BotonVerContraseñaPantallaPrincipal = new javax.swing.JButton();
        LabelUsuarioPantallaPrincipal = new javax.swing.JLabel();
        LabelContraseñaPantallaPrincipal = new javax.swing.JLabel();
        TextContraseñaPantallaPrincipal = new javax.swing.JPasswordField();
        PanelBotonesPantallaPrincipal = new javax.swing.JPanel();
        BotonAceptarPantallaPrincipal = new javax.swing.JButton();
        BotonRegistrarsePantallaPrincipal = new javax.swing.JButton();
        labelVerContraseñaPPrincipal = new javax.swing.JLabel();
        Registarse = new javax.swing.JFrame();
        PanelBienvenidos1 = new javax.swing.JPanel();
        PanelAeroTaxiPRegistrarse = new javax.swing.JPanel();
        LabelAeroTaxiPRegistrarse = new javax.swing.JLabel();
        LabelUsuarioPRegistrarse = new javax.swing.JLabel();
        LabelContraseñaPRegistrarse = new javax.swing.JLabel();
        TextContraseñaPRegistrarse = new javax.swing.JTextField();
        LabelNombrePRegistrarse = new javax.swing.JLabel();
        LabelApellidoPRegistrarse = new javax.swing.JLabel();
        LabelDNIPRegistrarse = new javax.swing.JLabel();
        LabelEdadPRegistrarse = new javax.swing.JLabel();
        TextUsuarioPRegistrarse = new javax.swing.JTextField();
        TextoNombrePRegistrarse = new javax.swing.JTextField();
        TextApellidoPRegistrarse = new javax.swing.JTextField();
        TextDNIPRegistrarse = new javax.swing.JTextField();
        TextEdadPRegistrarse = new javax.swing.JTextField();
        PanelBotonesPRegistrarse = new javax.swing.JPanel();
        BotonGuardarPRegistrarse = new javax.swing.JButton();
        BotonCancelarPRegistrarse = new javax.swing.JButton();
        Administrador = new javax.swing.JFrame();
        Fecha = new javax.swing.JFrame();
        PanelAeroTaxiPRegistrarse1 = new javax.swing.JPanel();
        LabelAeroTaxiPRegistrarse1 = new javax.swing.JLabel();
        PanelBotonesPRegistrarse1 = new javax.swing.JPanel();
        BotonSiguientePFecha = new javax.swing.JButton();
        BotonAtrasPFecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        OrigenDestino = new javax.swing.JFrame();
        PanelAeroTaxiPRegistrarse2 = new javax.swing.JPanel();
        LabelAeroTaxiPRegistrarse2 = new javax.swing.JLabel();
        PanelBotonesPRegistrarse2 = new javax.swing.JPanel();
        BotonSiguientePOrigen = new javax.swing.JButton();
        BotonAtrasPDestino = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        AvionesDisponibles = new javax.swing.JFrame();
        PanelAeroTaxiPRegistrarse3 = new javax.swing.JPanel();
        LabelAeroTaxiPRegistrarse3 = new javax.swing.JLabel();
        PanelBotonesPRegistrarse3 = new javax.swing.JPanel();
        BotonSiguientePAviones = new javax.swing.JButton();
        BotonAtrasPAviones = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        CostoVuelo = new javax.swing.JFrame();
        PanelAeroTaxiPRegistrarse4 = new javax.swing.JPanel();
        LabelAeroTaxiPRegistrarse4 = new javax.swing.JLabel();
        PanelBotonesPRegistrarse4 = new javax.swing.JPanel();
        BotonFinalizarPCosto = new javax.swing.JButton();
        BotonCancelarPRegistrarse1 = new javax.swing.JButton();
        BotonAtrasPCosto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Acompañantes = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        PanelBotonesPRegistrarse6 = new javax.swing.JPanel();
        BotonSiguientePAcompañantes = new javax.swing.JButton();
        BotonAtrasPAcompañantes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        PanelAeroTaxiPRegistrarse7 = new javax.swing.JPanel();
        LabelAeroTaxiPRegistrarse7 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        PanelBienvenidos = new javax.swing.JPanel();
        ConfortExcelencia = new javax.swing.JLabel();
        Bienvenidos = new javax.swing.JLabel();
        PanelAeroTaxi = new javax.swing.JPanel();
        AeroTaxi = new javax.swing.JLabel();
        PanelComenzar = new javax.swing.JPanel();
        BotonComenzar = new javax.swing.JButton();

        PanelBajoPantallaPrincipal.setBackground(new java.awt.Color(255, 255, 204));
        PanelBajoPantallaPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 153)));
        PanelBajoPantallaPrincipal.setForeground(new java.awt.Color(0, 153, 255));

        PanelAeroTaxiPantallaPrincipal.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxiPantallaPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxiPantallaPrincipal.setForeground(new java.awt.Color(0, 153, 204));

        LabelAeroTaxiPPrincipal.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LabelAeroTaxiPPrincipal.setText("A E R O T A X I   ");
        LabelAeroTaxiPPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiPantallaPrincipalLayout = new javax.swing.GroupLayout(PanelAeroTaxiPantallaPrincipal);
        PanelAeroTaxiPantallaPrincipal.setLayout(PanelAeroTaxiPantallaPrincipalLayout);
        PanelAeroTaxiPantallaPrincipalLayout.setHorizontalGroup(
                PanelAeroTaxiPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPantallaPrincipalLayout.createSequentialGroup()
                                .addContainerGap(75, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
        );
        PanelAeroTaxiPantallaPrincipalLayout.setVerticalGroup(
                PanelAeroTaxiPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAeroTaxiPantallaPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelAeroTaxiPPrincipal)
                                .addContainerGap(13, Short.MAX_VALUE))
        );

        TextUsuarioPantallaPrincipal.setText("Ingrese su Usuario");
        TextUsuarioPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioPantallaPrincipalActionPerformed(evt);
            }
        });

        BotonVerContraseñaPantallaPrincipal.setText("Ver Contraseña");
        BotonVerContraseñaPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerContraseñaPantallaPrincipalActionPerformed(evt);
            }
        });

        LabelUsuarioPantallaPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelUsuarioPantallaPrincipal.setText("Usuario:");

        LabelContraseñaPantallaPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelContraseñaPantallaPrincipal.setText("Contraseña:");

        TextContraseñaPantallaPrincipal.setText("Ingrese su Contraseña");
        TextContraseñaPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextContraseñaPantallaPrincipalActionPerformed(evt);
            }
        });

        PanelBotonesPantallaPrincipal.setBackground(new java.awt.Color(0, 153, 255));
        PanelBotonesPantallaPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelBotonesPantallaPrincipal.setForeground(new java.awt.Color(0, 153, 153));

        BotonAceptarPantallaPrincipal.setText("Aceptar");
        BotonAceptarPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarPantallaPrincipalActionPerformed(evt);
            }
        });

        BotonRegistrarsePantallaPrincipal.setText("Registrarse");
        BotonRegistrarsePantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarsePantallaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesPantallaPrincipalLayout = new javax.swing.GroupLayout(PanelBotonesPantallaPrincipal);
        PanelBotonesPantallaPrincipal.setLayout(PanelBotonesPantallaPrincipalLayout);
        PanelBotonesPantallaPrincipalLayout.setHorizontalGroup(
                PanelBotonesPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPantallaPrincipalLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(BotonAceptarPantallaPrincipal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonRegistrarsePantallaPrincipal)
                                .addGap(128, 128, 128))
        );
        PanelBotonesPantallaPrincipalLayout.setVerticalGroup(
                PanelBotonesPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPantallaPrincipalLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(PanelBotonesPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonAceptarPantallaPrincipal)
                                        .addComponent(BotonRegistrarsePantallaPrincipal))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelBajoPantallaPrincipalLayout = new javax.swing.GroupLayout(PanelBajoPantallaPrincipal);
        PanelBajoPantallaPrincipal.setLayout(PanelBajoPantallaPrincipalLayout);
        PanelBajoPantallaPrincipalLayout.setHorizontalGroup(
                PanelBajoPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBajoPantallaPrincipalLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(PanelBajoPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelContraseñaPantallaPrincipal)
                                        .addComponent(BotonVerContraseñaPantallaPrincipal)
                                        .addComponent(LabelUsuarioPantallaPrincipal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelBajoPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextContraseñaPantallaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextUsuarioPantallaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelVerContraseñaPPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94))
                        .addComponent(PanelAeroTaxiPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBotonesPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBajoPantallaPrincipalLayout.setVerticalGroup(
                PanelBajoPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBajoPantallaPrincipalLayout.createSequentialGroup()
                                .addComponent(PanelAeroTaxiPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addGroup(PanelBajoPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelUsuarioPantallaPrincipal)
                                        .addComponent(TextUsuarioPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelBajoPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelContraseñaPantallaPrincipal)
                                        .addComponent(TextContraseñaPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelBajoPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BotonVerContraseñaPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelVerContraseñaPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                                .addComponent(PanelBotonesPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PantallaPrincipalLayout = new javax.swing.GroupLayout(PantallaPrincipal.getContentPane());
        PantallaPrincipal.getContentPane().setLayout(PantallaPrincipalLayout);
        PantallaPrincipalLayout.setHorizontalGroup(
                PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelBajoPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PantallaPrincipalLayout.setVerticalGroup(
                PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelBajoPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Registarse.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelBienvenidos1.setBackground(new java.awt.Color(255, 255, 204));
        PanelBienvenidos1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 153)));
        PanelBienvenidos1.setForeground(new java.awt.Color(0, 153, 255));

        PanelAeroTaxiPRegistrarse.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxiPRegistrarse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxiPRegistrarse.setForeground(new java.awt.Color(0, 153, 204));

        LabelAeroTaxiPRegistrarse.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LabelAeroTaxiPRegistrarse.setText("A E R O T A X I  ");
        LabelAeroTaxiPRegistrarse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiPRegistrarseLayout = new javax.swing.GroupLayout(PanelAeroTaxiPRegistrarse);
        PanelAeroTaxiPRegistrarse.setLayout(PanelAeroTaxiPRegistrarseLayout);
        PanelAeroTaxiPRegistrarseLayout.setHorizontalGroup(
                PanelAeroTaxiPRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarseLayout.createSequentialGroup()
                                .addContainerGap(70, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
        );
        PanelAeroTaxiPRegistrarseLayout.setVerticalGroup(
                PanelAeroTaxiPRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAeroTaxiPRegistrarseLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelAeroTaxiPRegistrarse)
                                .addContainerGap(13, Short.MAX_VALUE))
        );

        LabelUsuarioPRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelUsuarioPRegistrarse.setText("Usuario:");

        LabelContraseñaPRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelContraseñaPRegistrarse.setText("Contraseña:");

        LabelNombrePRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNombrePRegistrarse.setText("Nombre");

        LabelApellidoPRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelApellidoPRegistrarse.setText("Apellido");

        LabelDNIPRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDNIPRegistrarse.setText("DNI");

        LabelEdadPRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelEdadPRegistrarse.setText("Edad");

        TextUsuarioPRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioPRegistrarseActionPerformed(evt);
            }
        });

        TextoNombrePRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombrePRegistrarseActionPerformed(evt);
            }
        });
        TextoNombrePRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextoNombrePRegistrarseKeyTyped(evt);
            }
        });

        TextApellidoPRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidoPRegistrarseActionPerformed(evt);
            }
        });
        TextApellidoPRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextApellidoPRegistrarseKeyTyped(evt);
            }
        });

        TextDNIPRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDNIPRegistrarseActionPerformed(evt);
            }
        });
        TextDNIPRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDNIPRegistrarseKeyTyped(evt);
            }
        });

        TextEdadPRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEdadPRegistrarseActionPerformed(evt);
            }
        });
        TextEdadPRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextEdadPRegistrarseKeyTyped(evt);
            }
        });

        PanelBotonesPRegistrarse.setBackground(new java.awt.Color(0, 153, 255));
        PanelBotonesPRegistrarse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelBotonesPRegistrarse.setForeground(new java.awt.Color(0, 153, 153));

        BotonGuardarPRegistrarse.setText("Guardar");
        BotonGuardarPRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarPRegistrarseActionPerformed(evt);
            }
        });

        BotonCancelarPRegistrarse.setText("Cancelar");
        BotonCancelarPRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarPRegistrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesPRegistrarseLayout = new javax.swing.GroupLayout(PanelBotonesPRegistrarse);
        PanelBotonesPRegistrarse.setLayout(PanelBotonesPRegistrarseLayout);
        PanelBotonesPRegistrarseLayout.setHorizontalGroup(
                PanelBotonesPRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarseLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BotonGuardarPRegistrarse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonCancelarPRegistrarse)
                                .addGap(148, 148, 148))
        );
        PanelBotonesPRegistrarseLayout.setVerticalGroup(
                PanelBotonesPRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarseLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(PanelBotonesPRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonGuardarPRegistrarse)
                                        .addComponent(BotonCancelarPRegistrarse))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelBienvenidos1Layout = new javax.swing.GroupLayout(PanelBienvenidos1);
        PanelBienvenidos1.setLayout(PanelBienvenidos1Layout);
        PanelBienvenidos1Layout.setHorizontalGroup(
                PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAeroTaxiPRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelBienvenidos1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelBienvenidos1Layout.createSequentialGroup()
                                                .addComponent(LabelEdadPRegistrarse)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextEdadPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelBienvenidos1Layout.createSequentialGroup()
                                                .addComponent(LabelDNIPRegistrarse)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextDNIPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelBienvenidos1Layout.createSequentialGroup()
                                                .addComponent(LabelApellidoPRegistrarse)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextApellidoPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelBienvenidos1Layout.createSequentialGroup()
                                                .addComponent(LabelNombrePRegistrarse)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextoNombrePRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelBienvenidos1Layout.createSequentialGroup()
                                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LabelUsuarioPRegistrarse)
                                                        .addComponent(LabelContraseñaPRegistrarse))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TextUsuarioPRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TextContraseñaPRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40))
                        .addComponent(PanelBotonesPRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBienvenidos1Layout.setVerticalGroup(
                PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBienvenidos1Layout.createSequentialGroup()
                                .addComponent(PanelAeroTaxiPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelUsuarioPRegistrarse)
                                        .addComponent(TextUsuarioPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelContraseñaPRegistrarse)
                                        .addComponent(TextContraseñaPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelNombrePRegistrarse)
                                        .addComponent(TextoNombrePRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelApellidoPRegistrarse)
                                        .addComponent(TextApellidoPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelDNIPRegistrarse)
                                        .addComponent(TextDNIPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(PanelBienvenidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelEdadPRegistrarse)
                                        .addComponent(TextEdadPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addComponent(PanelBotonesPRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout RegistarseLayout = new javax.swing.GroupLayout(Registarse.getContentPane());
        Registarse.getContentPane().setLayout(RegistarseLayout);
        RegistarseLayout.setHorizontalGroup(
                RegistarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelBienvenidos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegistarseLayout.setVerticalGroup(
                RegistarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelBienvenidos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AdministradorLayout = new javax.swing.GroupLayout(Administrador.getContentPane());
        Administrador.getContentPane().setLayout(AdministradorLayout);
        AdministradorLayout.setHorizontalGroup(
                AdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        AdministradorLayout.setVerticalGroup(
                AdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        PanelAeroTaxiPRegistrarse1.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxiPRegistrarse1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxiPRegistrarse1.setForeground(new java.awt.Color(0, 153, 204));

        LabelAeroTaxiPRegistrarse1.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LabelAeroTaxiPRegistrarse1.setText("A E R O T A X I  ");
        LabelAeroTaxiPRegistrarse1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiPRegistrarse1Layout = new javax.swing.GroupLayout(PanelAeroTaxiPRegistrarse1);
        PanelAeroTaxiPRegistrarse1.setLayout(PanelAeroTaxiPRegistrarse1Layout);
        PanelAeroTaxiPRegistrarse1Layout.setHorizontalGroup(
                PanelAeroTaxiPRegistrarse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse1Layout.createSequentialGroup()
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
        );
        PanelAeroTaxiPRegistrarse1Layout.setVerticalGroup(
                PanelAeroTaxiPRegistrarse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse1Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse1)
                                .addContainerGap())
        );

        PanelBotonesPRegistrarse1.setBackground(new java.awt.Color(0, 153, 255));
        PanelBotonesPRegistrarse1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelBotonesPRegistrarse1.setForeground(new java.awt.Color(0, 153, 153));

        BotonSiguientePFecha.setText("Siguiente");
        BotonSiguientePFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguientePFechaActionPerformed(evt);
            }
        });

        BotonAtrasPFecha.setText("Atras");
        BotonAtrasPFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasPFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesPRegistrarse1Layout = new javax.swing.GroupLayout(PanelBotonesPRegistrarse1);
        PanelBotonesPRegistrarse1.setLayout(PanelBotonesPRegistrarse1Layout);
        PanelBotonesPRegistrarse1Layout.setHorizontalGroup(
                PanelBotonesPRegistrarse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BotonSiguientePFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonAtrasPFecha)
                                .addGap(148, 148, 148))
        );
        PanelBotonesPRegistrarse1Layout.setVerticalGroup(
                PanelBotonesPRegistrarse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(PanelBotonesPRegistrarse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonSiguientePFecha)
                                        .addComponent(BotonAtrasPFecha))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("Fecha de Salida  ");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1623446520000L), java.util.Calendar.WEEK_OF_YEAR));

        javax.swing.GroupLayout FechaLayout = new javax.swing.GroupLayout(Fecha.getContentPane());
        Fecha.getContentPane().setLayout(FechaLayout);
        FechaLayout.setHorizontalGroup(
                FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAeroTaxiPRegistrarse1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBotonesPRegistrarse1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FechaLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FechaLayout.setVerticalGroup(
                FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FechaLayout.createSequentialGroup()
                                .addComponent(PanelAeroTaxiPRegistrarse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addComponent(PanelBotonesPRegistrarse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelAeroTaxiPRegistrarse2.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxiPRegistrarse2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxiPRegistrarse2.setForeground(new java.awt.Color(0, 153, 204));

        LabelAeroTaxiPRegistrarse2.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LabelAeroTaxiPRegistrarse2.setText("A E R O T A X I  ");
        LabelAeroTaxiPRegistrarse2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiPRegistrarse2Layout = new javax.swing.GroupLayout(PanelAeroTaxiPRegistrarse2);
        PanelAeroTaxiPRegistrarse2.setLayout(PanelAeroTaxiPRegistrarse2Layout);
        PanelAeroTaxiPRegistrarse2Layout.setHorizontalGroup(
                PanelAeroTaxiPRegistrarse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
        );
        PanelAeroTaxiPRegistrarse2Layout.setVerticalGroup(
                PanelAeroTaxiPRegistrarse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse2Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse2)
                                .addContainerGap())
        );

        PanelBotonesPRegistrarse2.setBackground(new java.awt.Color(0, 153, 255));
        PanelBotonesPRegistrarse2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelBotonesPRegistrarse2.setForeground(new java.awt.Color(0, 153, 153));

        BotonSiguientePOrigen.setText("Siguiente");
        BotonSiguientePOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguientePOrigenActionPerformed(evt);
            }
        });

        BotonAtrasPDestino.setText("Atras");
        BotonAtrasPDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasPDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesPRegistrarse2Layout = new javax.swing.GroupLayout(PanelBotonesPRegistrarse2);
        PanelBotonesPRegistrarse2.setLayout(PanelBotonesPRegistrarse2Layout);
        PanelBotonesPRegistrarse2Layout.setHorizontalGroup(
                PanelBotonesPRegistrarse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BotonSiguientePOrigen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonAtrasPDestino)
                                .addGap(148, 148, 148))
        );
        PanelBotonesPRegistrarse2Layout.setVerticalGroup(
                PanelBotonesPRegistrarse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(PanelBotonesPRegistrarse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonSiguientePOrigen)
                                        .addComponent(BotonAtrasPDestino))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("Destino");

        jLabel3.setText("Origen");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout OrigenDestinoLayout = new javax.swing.GroupLayout(OrigenDestino.getContentPane());
        OrigenDestino.getContentPane().setLayout(OrigenDestinoLayout);
        OrigenDestinoLayout.setHorizontalGroup(
                OrigenDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAeroTaxiPRegistrarse2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBotonesPRegistrarse2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrigenDestinoLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(OrigenDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(140, 140, 140))
                        .addGroup(OrigenDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(OrigenDestinoLayout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(325, Short.MAX_VALUE)))
        );
        OrigenDestinoLayout.setVerticalGroup(
                OrigenDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OrigenDestinoLayout.createSequentialGroup()
                                .addComponent(PanelAeroTaxiPRegistrarse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(OrigenDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                                .addComponent(PanelBotonesPRegistrarse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(OrigenDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(OrigenDestinoLayout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(356, Short.MAX_VALUE)))
        );

        PanelAeroTaxiPRegistrarse3.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxiPRegistrarse3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxiPRegistrarse3.setForeground(new java.awt.Color(0, 153, 204));

        LabelAeroTaxiPRegistrarse3.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LabelAeroTaxiPRegistrarse3.setText("A E R O T A X I  ");
        LabelAeroTaxiPRegistrarse3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiPRegistrarse3Layout = new javax.swing.GroupLayout(PanelAeroTaxiPRegistrarse3);
        PanelAeroTaxiPRegistrarse3.setLayout(PanelAeroTaxiPRegistrarse3Layout);
        PanelAeroTaxiPRegistrarse3Layout.setHorizontalGroup(
                PanelAeroTaxiPRegistrarse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAeroTaxiPRegistrarse3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(LabelAeroTaxiPRegistrarse3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAeroTaxiPRegistrarse3Layout.setVerticalGroup(
                PanelAeroTaxiPRegistrarse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse3Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse3)
                                .addContainerGap())
        );

        PanelBotonesPRegistrarse3.setBackground(new java.awt.Color(0, 153, 255));
        PanelBotonesPRegistrarse3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelBotonesPRegistrarse3.setForeground(new java.awt.Color(0, 153, 153));

        BotonSiguientePAviones.setText("Siguiente");
        BotonSiguientePAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguientePAvionesActionPerformed(evt);
            }
        });

        BotonAtrasPAviones.setText("Atras");
        BotonAtrasPAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasPAvionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesPRegistrarse3Layout = new javax.swing.GroupLayout(PanelBotonesPRegistrarse3);
        PanelBotonesPRegistrarse3.setLayout(PanelBotonesPRegistrarse3Layout);
        PanelBotonesPRegistrarse3Layout.setHorizontalGroup(
                PanelBotonesPRegistrarse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BotonSiguientePAviones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonAtrasPAviones)
                                .addGap(148, 148, 148))
        );
        PanelBotonesPRegistrarse3Layout.setVerticalGroup(
                PanelBotonesPRegistrarse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(PanelBotonesPRegistrarse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonSiguientePAviones)
                                        .addComponent(BotonAtrasPAviones))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aviones Disponibles Para La Fecha Elegida");

        jLabel5.setText("Aviones");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout AvionesDisponiblesLayout = new javax.swing.GroupLayout(AvionesDisponibles.getContentPane());
        AvionesDisponibles.getContentPane().setLayout(AvionesDisponiblesLayout);
        AvionesDisponiblesLayout.setHorizontalGroup(
                AvionesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAeroTaxiPRegistrarse3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBotonesPRegistrarse3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AvionesDisponiblesLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                        .addGroup(AvionesDisponiblesLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        AvionesDisponiblesLayout.setVerticalGroup(
                AvionesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AvionesDisponiblesLayout.createSequentialGroup()
                                .addComponent(PanelAeroTaxiPRegistrarse3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addGroup(AvionesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                                .addComponent(PanelBotonesPRegistrarse3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelAeroTaxiPRegistrarse4.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxiPRegistrarse4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxiPRegistrarse4.setForeground(new java.awt.Color(0, 153, 204));

        LabelAeroTaxiPRegistrarse4.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LabelAeroTaxiPRegistrarse4.setText("A E R O T A X I  ");
        LabelAeroTaxiPRegistrarse4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiPRegistrarse4Layout = new javax.swing.GroupLayout(PanelAeroTaxiPRegistrarse4);
        PanelAeroTaxiPRegistrarse4.setLayout(PanelAeroTaxiPRegistrarse4Layout);
        PanelAeroTaxiPRegistrarse4Layout.setHorizontalGroup(
                PanelAeroTaxiPRegistrarse4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse4Layout.createSequentialGroup()
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
        );
        PanelAeroTaxiPRegistrarse4Layout.setVerticalGroup(
                PanelAeroTaxiPRegistrarse4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse4Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse4)
                                .addContainerGap())
        );

        PanelBotonesPRegistrarse4.setBackground(new java.awt.Color(0, 153, 255));
        PanelBotonesPRegistrarse4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelBotonesPRegistrarse4.setForeground(new java.awt.Color(0, 153, 153));

        BotonFinalizarPCosto.setText("Finalizar");
        BotonFinalizarPCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFinalizarPCostoActionPerformed(evt);
            }
        });

        BotonCancelarPRegistrarse1.setText("Cancelar");
        BotonCancelarPRegistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarPRegistrarse1ActionPerformed(evt);
            }
        });

        BotonAtrasPCosto.setText("Atras");
        BotonAtrasPCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasPCostoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesPRegistrarse4Layout = new javax.swing.GroupLayout(PanelBotonesPRegistrarse4);
        PanelBotonesPRegistrarse4.setLayout(PanelBotonesPRegistrarse4Layout);
        PanelBotonesPRegistrarse4Layout.setHorizontalGroup(
                PanelBotonesPRegistrarse4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BotonFinalizarPCosto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonAtrasPCosto)
                                .addGap(18, 18, 18)
                                .addComponent(BotonCancelarPRegistrarse1)
                                .addGap(72, 72, 72))
        );
        PanelBotonesPRegistrarse4Layout.setVerticalGroup(
                PanelBotonesPRegistrarse4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(PanelBotonesPRegistrarse4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonFinalizarPCosto)
                                        .addComponent(BotonCancelarPRegistrarse1)
                                        .addComponent(BotonAtrasPCosto))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Costo del Viaje");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("$");

        javax.swing.GroupLayout CostoVueloLayout = new javax.swing.GroupLayout(CostoVuelo.getContentPane());
        CostoVuelo.getContentPane().setLayout(CostoVueloLayout);
        CostoVueloLayout.setHorizontalGroup(
                CostoVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelBotonesPRegistrarse4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CostoVueloLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(137, 137, 137))
                        .addComponent(PanelAeroTaxiPRegistrarse4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CostoVueloLayout.setVerticalGroup(
                CostoVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CostoVueloLayout.createSequentialGroup()
                                .addComponent(PanelAeroTaxiPRegistrarse4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addGroup(CostoVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                                .addComponent(PanelBotonesPRegistrarse4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cantidad de acompañantes");

        PanelBotonesPRegistrarse6.setBackground(new java.awt.Color(0, 153, 255));
        PanelBotonesPRegistrarse6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelBotonesPRegistrarse6.setForeground(new java.awt.Color(0, 153, 153));

        BotonSiguientePAcompañantes.setText("Siguiente");
        BotonSiguientePAcompañantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguientePAcompañantesActionPerformed(evt);
            }
        });

        BotonAtrasPAcompañantes.setText("Atras");
        BotonAtrasPAcompañantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasPAcompañantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesPRegistrarse6Layout = new javax.swing.GroupLayout(PanelBotonesPRegistrarse6);
        PanelBotonesPRegistrarse6.setLayout(PanelBotonesPRegistrarse6Layout);
        PanelBotonesPRegistrarse6Layout.setHorizontalGroup(
                PanelBotonesPRegistrarse6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse6Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BotonSiguientePAcompañantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonAtrasPAcompañantes)
                                .addGap(148, 148, 148))
        );
        PanelBotonesPRegistrarse6Layout.setVerticalGroup(
                PanelBotonesPRegistrarse6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBotonesPRegistrarse6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(PanelBotonesPRegistrarse6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonSiguientePAcompañantes)
                                        .addComponent(BotonAtrasPAcompañantes))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel9.setText("Acompañantes");

        PanelAeroTaxiPRegistrarse7.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxiPRegistrarse7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxiPRegistrarse7.setForeground(new java.awt.Color(0, 153, 204));

        LabelAeroTaxiPRegistrarse7.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LabelAeroTaxiPRegistrarse7.setText("A E R O T A X I  ");
        LabelAeroTaxiPRegistrarse7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiPRegistrarse7Layout = new javax.swing.GroupLayout(PanelAeroTaxiPRegistrarse7);
        PanelAeroTaxiPRegistrarse7.setLayout(PanelAeroTaxiPRegistrarse7Layout);
        PanelAeroTaxiPRegistrarse7Layout.setHorizontalGroup(
                PanelAeroTaxiPRegistrarse7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAeroTaxiPRegistrarse7Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(LabelAeroTaxiPRegistrarse7, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
        );
        PanelAeroTaxiPRegistrarse7Layout.setVerticalGroup(
                PanelAeroTaxiPRegistrarse7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiPRegistrarse7Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(LabelAeroTaxiPRegistrarse7)
                                .addContainerGap())
        );

        javax.swing.GroupLayout AcompañantesLayout = new javax.swing.GroupLayout(Acompañantes.getContentPane());
        Acompañantes.getContentPane().setLayout(AcompañantesLayout);
        AcompañantesLayout.setHorizontalGroup(
                AcompañantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAeroTaxiPRegistrarse7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBotonesPRegistrarse6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AcompañantesLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(AcompañantesLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        AcompañantesLayout.setVerticalGroup(
                AcompañantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AcompañantesLayout.createSequentialGroup()
                                .addComponent(PanelAeroTaxiPRegistrarse7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addGroup(AcompañantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                                .addComponent(PanelBotonesPRegistrarse6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelBienvenidos.setBackground(new java.awt.Color(255, 255, 204));
        PanelBienvenidos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 153)));
        PanelBienvenidos.setForeground(new java.awt.Color(0, 153, 255));

        ConfortExcelencia.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        ConfortExcelencia.setText(" Confort y Excelencia");
        ConfortExcelencia.setToolTipText("");

        Bienvenidos.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        Bienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenidos.setText("Bienvenidos");
        Bienvenidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PanelAeroTaxi.setBackground(new java.awt.Color(51, 153, 255));
        PanelAeroTaxi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        PanelAeroTaxi.setForeground(new java.awt.Color(0, 153, 204));

        AeroTaxi.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        AeroTaxi.setText("A E R O T A X I     ");
        AeroTaxi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelAeroTaxiLayout = new javax.swing.GroupLayout(PanelAeroTaxi);
        PanelAeroTaxi.setLayout(PanelAeroTaxiLayout);
        PanelAeroTaxiLayout.setHorizontalGroup(
                PanelAeroTaxiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAeroTaxiLayout.createSequentialGroup()
                                .addGap(0, 18, Short.MAX_VALUE)
                                .addComponent(AeroTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelAeroTaxiLayout.setVerticalGroup(
                PanelAeroTaxiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAeroTaxiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AeroTaxi)
                                .addContainerGap(13, Short.MAX_VALUE))
        );

        PanelComenzar.setBackground(new java.awt.Color(0, 153, 255));
        PanelComenzar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));
        PanelComenzar.setForeground(new java.awt.Color(0, 153, 153));

        BotonComenzar.setBackground(new java.awt.Color(255, 255, 255));
        BotonComenzar.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        BotonComenzar.setText("Comenzar");
        BotonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelComenzarLayout = new javax.swing.GroupLayout(PanelComenzar);
        PanelComenzar.setLayout(PanelComenzarLayout);
        PanelComenzarLayout.setHorizontalGroup(
                PanelComenzarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelComenzarLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(BotonComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelComenzarLayout.setVerticalGroup(
                PanelComenzarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComenzarLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout PanelBienvenidosLayout = new javax.swing.GroupLayout(PanelBienvenidos);
        PanelBienvenidos.setLayout(PanelBienvenidosLayout);
        PanelBienvenidosLayout.setHorizontalGroup(
                PanelBienvenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBienvenidosLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(Bienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(PanelAeroTaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelComenzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBienvenidosLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ConfortExcelencia, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
        );
        PanelBienvenidosLayout.setVerticalGroup(
                PanelBienvenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBienvenidosLayout.createSequentialGroup()
                                .addComponent(PanelAeroTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(ConfortExcelencia)
                                .addGap(71, 71, 71)
                                .addComponent(Bienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(PanelComenzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelBienvenidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelBienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void BotonComenzarActionPerformed(java.awt.event.ActionEvent evt) {

        JFrame jFrame22 = PantallaPrincipal;
        dispose();
        jFrame22.setSize(560,660);
        jFrame22.setTitle("Pantalla Principal");


        jFrame22.setVisible(true);

    }

    private void TextUsuarioPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void BotonVerContraseñaPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String contraseña = TextContraseñaPantallaPrincipal.getText();
        labelVerContraseñaPPrincipal.setText(contraseña);


    }

    private void TextContraseñaPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void BotonRegistrarsePantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = Registarse;
        dispose();
        JFrame jFrame22 = PantallaPrincipal;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Registrandose");


        jFrame11.setVisible(true);

    }

    private void BotonAceptarPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = Fecha;
        JFrame jFrame22 = PantallaPrincipal;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Fecha");


        jFrame11.setVisible(true);
    }

    private void BotonGuardarPRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame22 = PantallaPrincipal;
        JFrame jFrame11= Registarse;

        try {
            if (!archivo.exists()) {


//                System.out.println("El archivo no existe, Creando uno...");

                archivo.createNewFile();

//                System.out.println("Archivo " + archivo.getName() + " creado con exito");

            }




            if (archivo.getName().endsWith("json")) {


                usuario.setMiusuario(TextUsuarioPRegistrarse.getText());
                usuario.setContraseña(TextContraseñaPRegistrarse.getText());
                usuario.setNombre(TextoNombrePRegistrarse.getText());
                usuario.setApellido(TextApellidoPRegistrarse.getText());
                usuario.setDNI(TextDNIPRegistrarse.getText());
                usuario.setEdad(TextEdadPRegistrarse.getText());


                String s = objGson.toJson(usuario);


                String mensaje = GuardarArchivo(archivo, s);

                if (mensaje != null) {
                    JOptionPane.showMessageDialog(null, mensaje);
                } else {

                    JOptionPane.showMessageDialog(null, "No es Posible hacer el registro");
                }
            }


        }catch (IOException e){};
        jFrame11.setVisible(false);
        jFrame22.setSize(560,660);
        jFrame22.setTitle("Pantalla Principal");




        jFrame22.setVisible(true);
    }

    private void BotonCancelarPRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame22 = PantallaPrincipal;
        JFrame jFrame11= Registarse;
        jFrame11.setVisible(false);
        jFrame22.setSize(560,660);
        jFrame22.setTitle("Pantalla Principal");


        jFrame22.setVisible(true);
    }

    private void TextUsuarioPRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TextoNombrePRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TextApellidoPRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TextEdadPRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TextDNIPRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        ///Para no permitir ingresar letras
        char validar  = evt.getKeyChar();

        if(Character.isLetter(validar)){

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog (rootPane, "Ingresar Solo Numeros");
        }
    }

    private void TextEdadPRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog (rootPane , "Ingresar Solo Numeros");
        }
    }

    private void TextApellidoPRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Letras");
        }
    }

    private void TextoNombrePRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){

            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Letras");
        }
    }

    private void TextDNIPRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void BotonSiguientePFechaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = Fecha;
        JFrame jFrame22 = OrigenDestino;

        jFrame22.setVisible(true);
        jFrame22.setSize(560,660);
        jFrame22.setTitle("Lugar de Origen y Destino del Viaje");


        jFrame11.setVisible(false);
    }

    private void BotonAtrasPFechaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = PantallaPrincipal;
        JFrame jFrame22 = Fecha;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Pantalla Principal");


        jFrame11.setVisible(true);

    }

    private void BotonAtrasPDestinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = Fecha;
        JFrame jFrame22 = OrigenDestino;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Fecha Disponible");


        jFrame11.setVisible(true);


    }

    private void BotonSiguientePOrigenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = Acompañantes;

        JFrame jFrame22 = OrigenDestino;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Acompañantes");


        jFrame11.setVisible(true);


    }

    private void BotonSiguientePAvionesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame22 = AvionesDisponibles;
        dispose();
        JFrame jFrame11 = CostoVuelo;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Costo");


        jFrame11.setVisible(true);

    }

    private void BotonAtrasPAvionesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame22 = AvionesDisponibles;
        dispose();
        JFrame jFrame11 = Acompañantes;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Cantidad de Acompañantes");


        jFrame11.setVisible(true);

    }

    private void BotonFinalizarPCostoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(rootPane, "El Vuelo Fue Reservado Con Éxito");
        JFrame jFrame22 = CostoVuelo;
        dispose();
        JFrame jFrame11 = PantallaPrincipal;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Pantalla Principal");


        jFrame11.setVisible(true);
    }

    private void BotonCancelarPRegistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame22 = CostoVuelo;
        dispose();
        JFrame jFrame11 = PantallaPrincipal;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Pantalla Principal");


        jFrame11.setVisible(true);

    }

    private void BotonAtrasPCostoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame22 = CostoVuelo;
        dispose();
        JFrame jFrame11 = AvionesDisponibles;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Aviones Disponibles");


        jFrame11.setVisible(true);

    }

    private void BotonSiguientePAcompañantesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = AvionesDisponibles;
        dispose();
        JFrame jFrame22 = Acompañantes;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Aviones Disponibles");


        jFrame11.setVisible(true);
    }

    private void BotonAtrasPAcompañantesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame jFrame11 = OrigenDestino;
        dispose();
        JFrame jFrame22 = Acompañantes;

        jFrame22.setVisible(false);
        jFrame11.setSize(560,660);
        jFrame11.setTitle("Origen y Destino de viaje");


        jFrame11.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JFrame Acompañantes;
    private javax.swing.JFrame Administrador;
    private javax.swing.JLabel AeroTaxi;
    private javax.swing.JFrame AvionesDisponibles;
    private javax.swing.JLabel Bienvenidos;
    private javax.swing.JButton BotonAceptarPantallaPrincipal;
    private javax.swing.JButton BotonAtrasPAcompañantes;
    private javax.swing.JButton BotonAtrasPAviones;
    private javax.swing.JButton BotonAtrasPCosto;
    private javax.swing.JButton BotonAtrasPCosto1;
    private javax.swing.JButton BotonAtrasPDestino;
    private javax.swing.JButton BotonAtrasPFecha;
    private javax.swing.JButton BotonCancelarPRegistrarse;
    private javax.swing.JButton BotonCancelarPRegistrarse1;
    private javax.swing.JButton BotonCancelarPRegistrarse2;
    private javax.swing.JButton BotonComenzar;
    private javax.swing.JButton BotonFinalizarPCosto;
    private javax.swing.JButton BotonFinalizarPCosto1;
    private javax.swing.JButton BotonGuardarPRegistrarse;
    private javax.swing.JButton BotonRegistrarsePantallaPrincipal;
    private javax.swing.JButton BotonSiguientePAcompañantes;
    private javax.swing.JButton BotonSiguientePAviones;
    private javax.swing.JButton BotonSiguientePFecha;
    private javax.swing.JButton BotonSiguientePOrigen;
    private javax.swing.JButton BotonVerContraseñaPantallaPrincipal;
    private javax.swing.JLabel ConfortExcelencia;
    private javax.swing.JFrame CostoVuelo;
    private javax.swing.JFrame Fecha;
    private javax.swing.JLabel LabelAeroTaxiPPrincipal;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse1;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse2;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse3;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse4;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse5;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse6;
    private javax.swing.JLabel LabelAeroTaxiPRegistrarse7;
    private javax.swing.JLabel LabelApellidoPRegistrarse;
    private javax.swing.JLabel LabelContraseñaPRegistrarse;
    private javax.swing.JLabel LabelContraseñaPantallaPrincipal;
    private javax.swing.JLabel LabelDNIPRegistrarse;
    private javax.swing.JLabel LabelEdadPRegistrarse;
    private javax.swing.JLabel LabelNombrePRegistrarse;
    private javax.swing.JLabel LabelUsuarioPRegistrarse;
    private javax.swing.JLabel LabelUsuarioPantallaPrincipal;
    private javax.swing.JFrame OrigenDestino;
    private javax.swing.JPanel PanelAeroTaxi;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse1;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse2;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse3;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse4;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse5;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse6;
    private javax.swing.JPanel PanelAeroTaxiPRegistrarse7;
    private javax.swing.JPanel PanelAeroTaxiPantallaPrincipal;
    private javax.swing.JPanel PanelBajoPantallaPrincipal;
    private javax.swing.JPanel PanelBienvenidos;
    private javax.swing.JPanel PanelBienvenidos1;
    private javax.swing.JPanel PanelBotonesPRegistrarse;
    private javax.swing.JPanel PanelBotonesPRegistrarse1;
    private javax.swing.JPanel PanelBotonesPRegistrarse2;
    private javax.swing.JPanel PanelBotonesPRegistrarse3;
    private javax.swing.JPanel PanelBotonesPRegistrarse4;
    private javax.swing.JPanel PanelBotonesPRegistrarse5;
    private javax.swing.JPanel PanelBotonesPRegistrarse6;
    private javax.swing.JPanel PanelBotonesPantallaPrincipal;
    private javax.swing.JPanel PanelComenzar;
    private javax.swing.JFrame PantallaPrincipal;
    private javax.swing.JFrame Registarse;
    private javax.swing.JTextField TextApellidoPRegistrarse;
    private javax.swing.JTextField TextContraseñaPRegistrarse;
    private javax.swing.JPasswordField TextContraseñaPantallaPrincipal;
    private javax.swing.JTextField TextDNIPRegistrarse;
    private javax.swing.JTextField TextEdadPRegistrarse;
    private javax.swing.JTextField TextUsuarioPRegistrarse;
    private javax.swing.JTextField TextUsuarioPantallaPrincipal;
    private javax.swing.JTextField TextoNombrePRegistrarse;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel labelVerContraseñaPPrincipal;
    // End of variables declaration
}
